### ISSUE TITLE
when will release the code?

### ISSUE THREAD

**Issue by lcl-git-3d** [Shaosifan/FIANet#1]

**Comment by Shaosifan** [comment]
The code will be released before the next week.

**Comment by lcl-git-3d** [comment]
Thanks

**Comment by Magic-lem** [comment]
When will the code be released?    Thanks

**Comment by Shaosifan** [comment]
Sorry, the code will be released after the acceptance of this paper.

**Comment by Shaosifan** [comment]
> When will the code be released? Thanks

The code has been released.

**Comment by Shaosifan** [comment]
> when will release the code?

The code has been released.
